import { StyleSheet } from 'react-native';

import type { ThemeProfile } from './theme';

export function createStyles(theme: ThemeProfile) {
  const p = theme.palette;
  const shape = theme.shape;
  const surfaceLift = {
    shadowColor: theme.effect.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: theme.effect.shadowOpacity,
    shadowRadius: theme.effect.shadowRadius,
    elevation: theme.effect.elevation,
  };
  const accentLift = {
    shadowColor: theme.effect.accentShadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: theme.effect.accentShadowOpacity,
    shadowRadius: theme.effect.accentShadowRadius,
    elevation: theme.effect.accentElevation,
  };

  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: p.background,
    },
    screen: {
      flex: 1,
      backgroundColor: p.background,
    },
    screenContent: {
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 4,
      paddingBottom: 104,
    },
    screenContentImmersive: {
      minHeight: '100%',
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 0,
      paddingBottom: 96,
    },
    header: {
      gap: 3,
    },
    headerImmersive: {
      gap: 6,
      paddingHorizontal: 2,
    },
    screenTitleBlock: {
      gap: 1,
      paddingTop: 8,
      paddingHorizontal: 2,
    },
    screenTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 22,
      lineHeight: 25,
      letterSpacing: 0,
    },
    screenSubtitle: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_400Regular',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0,
    },
    roomTopBar: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      marginHorizontal: -16,
      paddingHorizontal: 16,
      paddingVertical: 7,
      borderBottomWidth: 1,
      borderColor: p.line,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    roomTopIcon: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      backgroundColor: p.overlayStrong,
    },
    roomTopCopy: {
      flex: 1,
      gap: 1,
    },
    roomTopLabel: {
      color: p.subtleText,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 9,
      letterSpacing: 0,
    },
    roomTopStatus: {
      color: p.accent,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 8,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    roomAvatar: {
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: p.accent,
      borderRadius: 15,
      backgroundColor: p.accent,
      ...accentLift,
    },
    roomAvatarText: {
      color: p.onAccent,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 10,
      letterSpacing: 0,
    },
    eyebrow: {
      color: p.accent,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 10,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    title: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 25,
      lineHeight: 28,
      letterSpacing: 0,
    },
    poster: {
      minHeight: 414,
      justifyContent: 'space-between',
      gap: 18,
      padding: 22,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...surfaceLift,
    },
    heroShowcase: {
      borderColor: p.accentAlt,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    heroMarquee: {
      minHeight: 42,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
    },
    heroMarqueeText: {
      color: p.foreground,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    heroMarqueeAccent: {
      color: p.warning,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    rowBetween: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    heroCopy: {
      gap: 8,
    },
    heroCopyCentered: {
      alignItems: 'center',
    },
    heroTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 31,
      lineHeight: 33,
      letterSpacing: 0,
    },
    bodyText: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_400Regular',
      fontSize: 12,
      lineHeight: 17,
      letterSpacing: 0,
    },
    centeredBodyText: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_400Regular',
      fontSize: 12,
      lineHeight: 17,
      letterSpacing: 0,
      textAlign: 'center',
    },
    luminousHeroPanel: {
      minHeight: 142,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    gradientPanel: {
      gap: 10,
      padding: 15,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      overflow: 'hidden',
      ...accentLift,
    },
    gradientPanelTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 25,
      lineHeight: 27,
      letterSpacing: 0,
    },
    gradientPanelMeta: {
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 9,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    luminousHeroTitle: {
      color: p.accentAlt,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 25,
      lineHeight: 27,
      letterSpacing: 0,
      textAlign: 'center',
    },
    luminousHeroMeta: {
      color: p.accent,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 9,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    luminousHeroOrb: {
      width: 50,
      height: 50,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: p.accent,
      borderRadius: 25,
      backgroundColor: p.overlayStrong,
      ...accentLift,
    },
    luminousHeroOrbText: {
      color: p.accent,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 18,
      letterSpacing: 0,
    },
    tokenRow: {
      flexDirection: 'row',
      gap: 10,
      height: 88,
    },
    token: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderRadius: shape.controlRadius,
      borderWidth: 1,
      borderColor: p.line,
      ...accentLift,
    },
    tokenText: {
      color: p.onAccent,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    cardCompact: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    roomEntryCard: {
      borderColor: p.action,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    welcomeBrand: {
      alignItems: 'center',
      gap: 3,
      paddingTop: 28,
      paddingBottom: 8,
    },
    welcomeBrandTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 34,
      lineHeight: 36,
      letterSpacing: 0,
      textAlign: 'center',
    },
    welcomeBrandAccent: {
      color: p.action,
    },
    codeSlots: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 7,
      paddingVertical: 4,
    },
    codeSlot: {
      width: 34,
      height: 44,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.input,
    },
    codeSlotFilled: {
      borderColor: p.action,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    codeSlotText: {
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 17,
      letterSpacing: 0,
    },
    featureStrip: {
      flexDirection: 'row',
      gap: 8,
    },
    featureTile: {
      flex: 1,
      minHeight: 64,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.surface,
    },
    featureTileText: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_600SemiBold',
      fontSize: 9,
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    bottomCtaWrap: {
      gap: 10,
      paddingTop: 6,
    },
    metaLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    codeText: {
      color: p.foreground,
      fontSize: 23,
      fontWeight: '900',
      letterSpacing: 0,
    },
    twoColumn: {
      flexDirection: 'row',
      gap: 10,
      minHeight: 58,
    },
    threeColumn: {
      flexDirection: 'row',
      gap: 8,
      minHeight: 48,
    },
    actionButton: {
      flex: 1,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: shape.controlRadius,
      borderWidth: 1,
      borderColor: p.line,
      ...surfaceLift,
    },
    actionButtonGradient: {
      flex: 1,
      width: '100%',
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: shape.controlRadius,
    },
    actionButtonPrimary: {
      borderColor: p.action,
      shadowColor: p.action,
      shadowOpacity: 0.42,
      shadowRadius: 16,
      elevation: 7,
    },
    actionButtonText: {
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 13,
      letterSpacing: 0,
    },
    stack: {
      gap: 10,
    },
    inputGroup: {
      gap: 7,
    },
    textInput: {
      minHeight: 48,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.input,
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_600SemiBold',
      fontSize: 15,
      letterSpacing: 0,
    },
    errorText: {
      color: p.danger,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
      letterSpacing: 0,
    },
    infoBanner: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderRadius: shape.cardRadius,
      borderWidth: 1,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    infoIconWrap: {
      width: 32,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
    },
    flex: {
      flex: 1,
    },
    infoTitle: {
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 15,
      letterSpacing: 0,
    },
    infoSubtitle: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_500Medium',
      fontSize: 11,
      letterSpacing: 0,
    },
    teamCard: {
      minHeight: 70,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    teamCardSelected: {
      minHeight: 76,
      backgroundColor: p.surfaceAlt,
      borderColor: p.accent,
      ...accentLift,
    },
    disabledCard: {
      opacity: theme.opacity.disabled,
    },
    teamGlyph: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: shape.controlRadius,
    },
    teamGlyphText: {
      color: p.onAccent,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 0,
    },
    teamName: {
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 14,
      letterSpacing: 0,
    },
    teamNameSelected: {
      color: p.foreground,
    },
    teamMeta: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_500Medium',
      fontSize: 11,
      letterSpacing: 0,
    },
    teamMetaSelected: {
      color: p.accent,
    },
    questionPanel: {
      minHeight: 220,
      justifyContent: 'space-between',
      gap: 16,
      padding: 18,
      borderRadius: shape.cardRadius,
      backgroundColor: p.info,
      ...accentLift,
    },
    questionPanelLuminous: {
      borderWidth: 1,
      borderColor: p.accentAlt,
      backgroundColor: p.surfaceAlt,
    },
    answerStagePanel: {
      minHeight: 250,
      justifyContent: 'space-between',
      gap: 18,
      padding: 20,
    },
    darkMeta: {
      color: p.onInfo,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    lightMeta: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    questionText: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 24,
      lineHeight: 27,
      letterSpacing: 0,
    },
    lockNote: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 10,
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlay,
    },
    lockText: {
      color: p.foreground,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    answerOption: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    answerSelected: {
      backgroundColor: p.accent,
      borderColor: p.accent,
      ...accentLift,
    },
    answerKey: {
      color: p.danger,
      fontSize: 16,
      fontWeight: '900',
      letterSpacing: 0,
    },
    answerKeySelected: {
      color: p.onAccent,
    },
    answerLabel: {
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_600SemiBold',
      fontSize: 14,
      letterSpacing: 0,
    },
    answerLabelSelected: {
      color: p.onAccent,
      fontWeight: '900',
    },
    podium: {
      minHeight: 150,
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 10,
    },
    podiumCard: {
      flex: 1,
      minHeight: 114,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    podiumWinner: {
      minHeight: 150,
      backgroundColor: p.surfaceAlt,
      borderColor: p.accent,
      ...accentLift,
    },
    podiumRank: {
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumName: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumPoints: {
      color: p.muted,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumTextDark: {
      color: p.foreground,
    },
    sectionTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_700Bold',
      fontSize: 16,
      letterSpacing: 0,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 2,
      paddingTop: 4,
    },
    scoreLogItem: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    scoreLogLabel: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0,
    },
    scoreLogDelta: {
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    scoreToast: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
      ...surfaceLift,
    },
    scoreToastDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: p.accent,
    },
    scoreToastLabel: {
      flex: 1,
      color: p.foreground,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    scoreToastDelta: {
      fontSize: 16,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roomCard: {
      minHeight: 132,
      justifyContent: 'space-between',
      gap: 14,
      padding: 14,
      borderRadius: shape.cardRadius,
      backgroundColor: p.accentAlt,
      ...accentLift,
    },
    roomCardSpotlight: {
      borderWidth: 1,
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
    },
    spotlightPanel: {
      gap: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...surfaceLift,
    },
    spotlightPanelAccent: {
      borderColor: p.accent,
      ...accentLift,
    },
    stageControlPanel: {
      gap: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: p.warning,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    stageGradientPanel: {
      minHeight: 174,
      justifyContent: 'space-between',
      gap: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: p.action,
      borderRadius: shape.cardRadius,
      overflow: 'hidden',
      ...accentLift,
    },
    timerHero: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 1,
      paddingVertical: 10,
    },
    timerHeroValue: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 45,
      lineHeight: 48,
      letterSpacing: 0,
    },
    stageTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 24,
      lineHeight: 27,
      letterSpacing: 0,
    },
    glowStrip: {
      height: 6,
      borderRadius: 999,
      backgroundColor: p.accentAlt,
    },
    metaLabelLight: {
      color: p.subtleText,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
    },
    bigCode: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 27,
      letterSpacing: 0,
    },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingHorizontal: 9,
      paddingVertical: 7,
      borderRadius: shape.pillRadius,
      backgroundColor: p.overlay,
    },
    pillDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    pillText: {
      color: p.foreground,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
    },
    statRow: {
      flexDirection: 'row',
      gap: 8,
      minHeight: 54,
    },
    stat: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    statValue: {
      color: p.foreground,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: 0,
    },
    statLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0,
    },
    card: {
      gap: 9,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    cardLuminous: {
      borderColor: p.line,
      backgroundColor: p.surfaceAlt,
    },
    cardAccent: {
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    cardAction: {
      borderColor: p.action,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    cardTitle: {
      color: p.foreground,
      fontFamily: 'Baloo2_700Bold',
      fontSize: 20,
      lineHeight: 23,
      letterSpacing: 0,
    },
    metaLabelAccent: {
      color: p.info,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
    },
    positiveText: {
      color: p.success,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundCard: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    roundSelected: {
      backgroundColor: p.surfaceAlt,
      borderColor: p.accent,
      ...accentLift,
    },
    roundNumber: {
      color: p.info,
      fontSize: 17,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundTextSelected: {
      color: p.accent,
    },
    roundTitle: {
      color: p.foreground,
      fontFamily: 'SpaceGrotesk_700Bold',
      fontSize: 13,
      letterSpacing: 0,
    },
    roundDetail: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_500Medium',
      fontSize: 10,
      letterSpacing: 0,
    },
    pointValue: {
      color: p.accent,
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 0,
    },
    smallButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
    },
    smallButtonText: {
      color: p.foreground,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    timerCard: {
      minHeight: 122,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderWidth: 1,
      borderColor: p.warning,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...surfaceLift,
    },
    timerText: {
      color: p.warning,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 42,
      letterSpacing: 0,
    },
    timerSubtext: {
      color: p.subtleText,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    secretCard: {
      minHeight: 174,
      justifyContent: 'space-between',
      gap: 10,
      padding: 16,
      borderRadius: shape.cardRadius,
      borderWidth: 1,
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    secretWord: {
      color: p.foreground,
      fontFamily: 'Baloo2_800ExtraBold',
      fontSize: 30,
      fontWeight: '900',
      letterSpacing: 0,
    },
    forbiddenWord: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
    },
    forbiddenText: {
      color: p.accent,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    navWrap: {
      height: 68,
      justifyContent: 'center',
      paddingTop: 7,
      paddingHorizontal: 16,
      paddingBottom: 8,
      backgroundColor: p.background,
    },
    navPill: {
      height: 50,
      flexDirection: 'row',
      gap: 4,
      padding: 4,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.overlayStrong,
      ...accentLift,
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderRadius: shape.controlRadius,
    },
    navItemActive: {
      backgroundColor: p.navActive,
      ...accentLift,
    },
    navLabel: {
      color: p.muted,
      fontFamily: 'SpaceGrotesk_600SemiBold',
      fontSize: 9,
      letterSpacing: 0,
    },
    navLabelActive: {
      color: p.onAccent,
      fontWeight: '900',
    },
  });
}
