import { StyleSheet } from 'react-native';

import type { ThemePalette } from './theme';

export function createStyles(p: ThemePalette) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: p.background,
    },
    screen: {
      flex: 1,
      backgroundColor: p.background,
    },
    screenContent: {
      gap: 14,
      paddingHorizontal: 18,
      paddingTop: 8,
      paddingBottom: 20,
    },
    header: {
      gap: 3,
    },
    eyebrow: {
      color: p.accent,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    title: {
      color: p.foreground,
      fontSize: 34,
      fontWeight: '900',
      letterSpacing: 0,
    },
    poster: {
      minHeight: 414,
      justifyContent: 'space-between',
      gap: 18,
      padding: 22,
      borderWidth: 1,
      borderColor: '#6B5BD6',
      borderRadius: 8,
      backgroundColor: p.surfaceAlt,
    },
    rowBetween: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    heroCopy: {
      gap: 8,
    },
    heroTitle: {
      color: p.foreground,
      fontSize: 41,
      fontWeight: '900',
      letterSpacing: 0,
    },
    bodyText: {
      color: p.muted,
      fontSize: 13,
      lineHeight: 17,
      letterSpacing: 0,
    },
    tokenRow: {
      flexDirection: 'row',
      gap: 10,
      height: 88,
    },
    token: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderRadius: 8,
    },
    tokenText: {
      color: p.ink,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    cardCompact: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    metaLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    codeText: {
      color: p.foreground,
      fontSize: 23,
      fontWeight: '900',
      letterSpacing: 0,
    },
    twoColumn: {
      flexDirection: 'row',
      gap: 10,
      minHeight: 58,
    },
    threeColumn: {
      flexDirection: 'row',
      gap: 8,
      minHeight: 48,
    },
    actionButton: {
      flex: 1,
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: p.line,
    },
    actionButtonText: {
      fontSize: 15,
      fontWeight: '900',
      letterSpacing: 0,
    },
    stack: {
      gap: 10,
    },
    infoBanner: {
      minHeight: 84,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 8,
    },
    flex: {
      flex: 1,
    },
    infoTitle: {
      color: p.ink,
      fontSize: 15,
      fontWeight: '900',
      letterSpacing: 0,
    },
    infoSubtitle: {
      color: '#173D38',
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    teamCard: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    teamCardSelected: {
      minHeight: 86,
      backgroundColor: p.accent,
      borderColor: p.accent,
    },
    teamGlyph: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
    },
    teamGlyphText: {
      color: p.ink,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 0,
    },
    teamName: {
      color: p.foreground,
      fontSize: 15,
      fontWeight: '900',
      letterSpacing: 0,
    },
    teamNameSelected: {
      color: p.ink,
    },
    teamMeta: {
      color: p.muted,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0,
    },
    teamMetaSelected: {
      color: '#5D4210',
    },
    questionPanel: {
      minHeight: 250,
      justifyContent: 'space-between',
      gap: 16,
      padding: 18,
      borderRadius: 8,
      backgroundColor: p.info,
    },
    darkMeta: {
      color: p.ink,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    lightMeta: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    questionText: {
      color: p.foreground,
      fontSize: 31,
      fontWeight: '900',
      lineHeight: 34,
      letterSpacing: 0,
    },
    lockNote: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 10,
      borderRadius: 8,
      backgroundColor: '#0D0A19AA',
    },
    lockText: {
      color: p.foreground,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    answerOption: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    answerSelected: {
      backgroundColor: p.accent,
      borderColor: p.accent,
    },
    answerKey: {
      color: p.danger,
      fontSize: 16,
      fontWeight: '900',
      letterSpacing: 0,
    },
    answerKeySelected: {
      color: p.ink,
    },
    answerLabel: {
      color: p.foreground,
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0,
    },
    answerLabelSelected: {
      color: p.ink,
      fontWeight: '900',
    },
    podium: {
      minHeight: 176,
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 10,
    },
    podiumCard: {
      flex: 1,
      minHeight: 114,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    podiumWinner: {
      minHeight: 176,
      backgroundColor: p.accent,
      borderColor: p.accent,
    },
    podiumRank: {
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumName: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumPoints: {
      color: p.muted,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumTextDark: {
      color: p.ink,
    },
    sectionTitle: {
      color: p.foreground,
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    scoreLogItem: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    scoreLogLabel: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0,
    },
    scoreLogDelta: {
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roomCard: {
      minHeight: 170,
      justifyContent: 'space-between',
      gap: 14,
      padding: 18,
      borderRadius: 8,
      backgroundColor: p.danger,
    },
    metaLabelLight: {
      color: '#FFE4F2',
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
    },
    bigCode: {
      color: p.foreground,
      fontSize: 29,
      fontWeight: '900',
      letterSpacing: 0,
    },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingHorizontal: 9,
      paddingVertical: 7,
      borderRadius: 8,
      backgroundColor: '#0D0A19AA',
    },
    pillDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    pillText: {
      color: p.foreground,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
    },
    statRow: {
      flexDirection: 'row',
      gap: 8,
      minHeight: 54,
    },
    stat: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    statValue: {
      color: p.foreground,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: 0,
    },
    statLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0,
    },
    card: {
      gap: 9,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    cardTitle: {
      color: p.foreground,
      fontSize: 23,
      fontWeight: '900',
      letterSpacing: 0,
    },
    metaLabelAccent: {
      color: p.info,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
    },
    positiveText: {
      color: p.success,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundCard: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 8,
      backgroundColor: p.surface,
    },
    roundSelected: {
      backgroundColor: p.accent,
      borderColor: p.accent,
    },
    roundNumber: {
      color: p.info,
      fontSize: 17,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundTextSelected: {
      color: p.ink,
    },
    roundTitle: {
      color: p.foreground,
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundDetail: {
      color: p.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0,
    },
    pointValue: {
      color: p.accent,
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 0,
    },
    smallButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: p.ink,
    },
    smallButtonText: {
      color: p.foreground,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    timerCard: {
      minHeight: 122,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderWidth: 1,
      borderColor: p.danger,
      borderRadius: 8,
      backgroundColor: p.surfaceAlt,
    },
    timerText: {
      color: p.foreground,
      fontSize: 44,
      fontWeight: '900',
      letterSpacing: 0,
    },
    timerSubtext: {
      color: '#F7CBE1',
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    secretCard: {
      minHeight: 174,
      justifyContent: 'space-between',
      gap: 10,
      padding: 16,
      borderRadius: 8,
      backgroundColor: p.accent,
    },
    secretWord: {
      color: p.ink,
      fontSize: 30,
      fontWeight: '900',
      letterSpacing: 0,
    },
    forbiddenWord: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: p.ink,
    },
    forbiddenText: {
      color: p.accent,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    navWrap: {
      height: 102,
      justifyContent: 'center',
      paddingTop: 12,
      paddingHorizontal: 21,
      paddingBottom: 21,
      backgroundColor: p.background,
    },
    navPill: {
      height: 62,
      flexDirection: 'row',
      gap: 2,
      padding: 4,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 36,
      backgroundColor: '#17123A',
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderRadius: 26,
    },
    navItemActive: {
      backgroundColor: p.accent,
    },
    navLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0,
    },
    navLabelActive: {
      color: p.ink,
      fontWeight: '900',
    },
  });
}
