import { StyleSheet } from 'react-native';

import type { ThemeProfile } from './theme';

export function createStyles(theme: ThemeProfile) {
  const p = theme.palette;
  const shape = theme.shape;
  const surfaceLift = {
    shadowColor: theme.effect.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: theme.effect.shadowOpacity,
    shadowRadius: theme.effect.shadowRadius,
    elevation: theme.effect.elevation,
  };
  const accentLift = {
    shadowColor: theme.effect.accentShadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: theme.effect.accentShadowOpacity,
    shadowRadius: theme.effect.accentShadowRadius,
    elevation: theme.effect.accentElevation,
  };

  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: p.background,
    },
    screen: {
      flex: 1,
      backgroundColor: p.background,
    },
    screenContent: {
      gap: 14,
      paddingHorizontal: 18,
      paddingTop: 8,
      paddingBottom: 224,
    },
    screenContentImmersive: {
      minHeight: '100%',
      gap: 16,
      paddingHorizontal: 16,
      paddingTop: 6,
      paddingBottom: 178,
    },
    header: {
      gap: 3,
    },
    headerImmersive: {
      gap: 6,
      paddingHorizontal: 2,
    },
    roomTopBar: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.pillRadius,
      backgroundColor: p.overlay,
      ...surfaceLift,
    },
    roomTopIcon: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 13,
      backgroundColor: p.overlayStrong,
    },
    roomTopCopy: {
      flex: 1,
      gap: 1,
    },
    roomTopLabel: {
      color: p.subtleText,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roomTopStatus: {
      color: p.accent,
      fontSize: 9,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    roomAvatar: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: p.accent,
      borderRadius: 16,
      backgroundColor: p.accent,
      ...accentLift,
    },
    roomAvatarText: {
      color: p.onAccent,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
    },
    eyebrow: {
      color: p.accent,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    title: {
      color: p.foreground,
      fontSize: 34,
      fontWeight: '900',
      letterSpacing: 0,
    },
    poster: {
      minHeight: 414,
      justifyContent: 'space-between',
      gap: 18,
      padding: 22,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...surfaceLift,
    },
    heroShowcase: {
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    heroMarquee: {
      minHeight: 42,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
    },
    heroMarqueeText: {
      color: p.foreground,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    heroMarqueeAccent: {
      color: p.accent,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    rowBetween: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    heroCopy: {
      gap: 8,
    },
    heroTitle: {
      color: p.foreground,
      fontSize: 41,
      fontWeight: '900',
      letterSpacing: 0,
    },
    bodyText: {
      color: p.muted,
      fontSize: 13,
      lineHeight: 17,
      letterSpacing: 0,
    },
    centeredBodyText: {
      color: p.muted,
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
      textAlign: 'center',
    },
    luminousHeroPanel: {
      minHeight: 214,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
      padding: 20,
      borderWidth: 1,
      borderColor: p.accent,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    luminousHeroTitle: {
      color: p.foreground,
      fontSize: 31,
      fontWeight: '900',
      lineHeight: 35,
      letterSpacing: 0,
      textAlign: 'center',
    },
    luminousHeroMeta: {
      color: p.accent,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    luminousHeroOrb: {
      width: 76,
      height: 76,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: p.accent,
      borderRadius: 38,
      backgroundColor: p.overlayStrong,
      ...accentLift,
    },
    luminousHeroOrbText: {
      color: p.accent,
      fontSize: 21,
      fontWeight: '900',
      letterSpacing: 0,
    },
    tokenRow: {
      flexDirection: 'row',
      gap: 10,
      height: 88,
    },
    token: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderRadius: shape.controlRadius,
      borderWidth: 1,
      borderColor: p.line,
      ...accentLift,
    },
    tokenText: {
      color: p.onAccent,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    cardCompact: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    roomEntryCard: {
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    bottomCtaWrap: {
      gap: 10,
      paddingTop: 6,
    },
    metaLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    codeText: {
      color: p.foreground,
      fontSize: 23,
      fontWeight: '900',
      letterSpacing: 0,
    },
    twoColumn: {
      flexDirection: 'row',
      gap: 10,
      minHeight: 58,
    },
    threeColumn: {
      flexDirection: 'row',
      gap: 8,
      minHeight: 48,
    },
    actionButton: {
      flex: 1,
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: shape.controlRadius,
      borderWidth: 1,
      borderColor: p.line,
      ...surfaceLift,
    },
    actionButtonText: {
      fontSize: 15,
      fontWeight: '900',
      letterSpacing: 0,
    },
    stack: {
      gap: 10,
    },
    inputGroup: {
      gap: 7,
    },
    textInput: {
      minHeight: 56,
      paddingHorizontal: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.input,
      color: p.foreground,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: 0,
    },
    errorText: {
      color: p.danger,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 16,
      letterSpacing: 0,
    },
    infoBanner: {
      minHeight: 84,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: shape.cardRadius,
      borderWidth: 1,
      borderColor: p.line,
      ...accentLift,
    },
    infoIconWrap: {
      width: 32,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
    },
    flex: {
      flex: 1,
    },
    infoTitle: {
      color: p.onInfo,
      fontSize: 15,
      fontWeight: '900',
      letterSpacing: 0,
    },
    infoSubtitle: {
      color: p.onInfo,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    teamCard: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    teamCardSelected: {
      minHeight: 86,
      backgroundColor: p.accent,
      borderColor: p.accent,
      ...accentLift,
    },
    disabledCard: {
      opacity: theme.opacity.disabled,
    },
    teamGlyph: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: shape.controlRadius,
    },
    teamGlyphText: {
      color: p.onAccent,
      fontSize: 20,
      fontWeight: '900',
      letterSpacing: 0,
    },
    teamName: {
      color: p.foreground,
      fontSize: 15,
      fontWeight: '900',
      letterSpacing: 0,
    },
    teamNameSelected: {
      color: p.onAccent,
    },
    teamMeta: {
      color: p.muted,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0,
    },
    teamMetaSelected: {
      color: p.onAccent,
    },
    questionPanel: {
      minHeight: 250,
      justifyContent: 'space-between',
      gap: 16,
      padding: 18,
      borderRadius: shape.cardRadius,
      backgroundColor: p.info,
      ...accentLift,
    },
    questionPanelLuminous: {
      borderWidth: 1,
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
    },
    answerStagePanel: {
      minHeight: 318,
      justifyContent: 'space-between',
      gap: 18,
      padding: 20,
    },
    darkMeta: {
      color: p.onInfo,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
      textTransform: 'uppercase',
    },
    lightMeta: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    questionText: {
      color: p.foreground,
      fontSize: 31,
      fontWeight: '900',
      lineHeight: 34,
      letterSpacing: 0,
    },
    lockNote: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 10,
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlay,
    },
    lockText: {
      color: p.foreground,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    answerOption: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    answerSelected: {
      backgroundColor: p.accent,
      borderColor: p.accent,
      ...accentLift,
    },
    answerKey: {
      color: p.danger,
      fontSize: 16,
      fontWeight: '900',
      letterSpacing: 0,
    },
    answerKeySelected: {
      color: p.onAccent,
    },
    answerLabel: {
      color: p.foreground,
      fontSize: 16,
      fontWeight: '800',
      letterSpacing: 0,
    },
    answerLabelSelected: {
      color: p.onAccent,
      fontWeight: '900',
    },
    podium: {
      minHeight: 176,
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 10,
    },
    podiumCard: {
      flex: 1,
      minHeight: 114,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    podiumWinner: {
      minHeight: 176,
      backgroundColor: p.accent,
      borderColor: p.accent,
      ...accentLift,
    },
    podiumRank: {
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumName: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumPoints: {
      color: p.muted,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    podiumTextDark: {
      color: p.onAccent,
    },
    sectionTitle: {
      color: p.foreground,
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 2,
      paddingTop: 4,
    },
    scoreLogItem: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    scoreLogLabel: {
      color: p.foreground,
      fontSize: 13,
      fontWeight: '800',
      letterSpacing: 0,
    },
    scoreLogDelta: {
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    scoreToast: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
      ...surfaceLift,
    },
    scoreToastDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: p.accent,
    },
    scoreToastLabel: {
      flex: 1,
      color: p.foreground,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    scoreToastDelta: {
      fontSize: 16,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roomCard: {
      minHeight: 170,
      justifyContent: 'space-between',
      gap: 14,
      padding: 18,
      borderRadius: shape.cardRadius,
      backgroundColor: p.danger,
      ...accentLift,
    },
    roomCardSpotlight: {
      borderWidth: 1,
      borderColor: p.accent,
      backgroundColor: p.surfaceAlt,
    },
    spotlightPanel: {
      gap: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...surfaceLift,
    },
    spotlightPanelAccent: {
      borderColor: p.accent,
      ...accentLift,
    },
    stageControlPanel: {
      gap: 14,
      padding: 16,
      borderWidth: 1,
      borderColor: p.accent,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...accentLift,
    },
    stageTitle: {
      color: p.foreground,
      fontSize: 27,
      fontWeight: '900',
      lineHeight: 31,
      letterSpacing: 0,
    },
    glowStrip: {
      height: 6,
      borderRadius: 999,
      backgroundColor: p.accent,
    },
    metaLabelLight: {
      color: p.subtleText,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
    },
    bigCode: {
      color: p.foreground,
      fontSize: 29,
      fontWeight: '900',
      letterSpacing: 0,
    },
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingHorizontal: 9,
      paddingVertical: 7,
      borderRadius: shape.pillRadius,
      backgroundColor: p.overlay,
    },
    pillDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    pillText: {
      color: p.foreground,
      fontSize: 10,
      fontWeight: '900',
      letterSpacing: 0,
    },
    statRow: {
      flexDirection: 'row',
      gap: 8,
      minHeight: 54,
    },
    stat: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    statValue: {
      color: p.foreground,
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: 0,
    },
    statLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 0,
    },
    card: {
      gap: 9,
      padding: 14,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    cardLuminous: {
      borderColor: p.line,
      backgroundColor: p.surfaceAlt,
    },
    cardTitle: {
      color: p.foreground,
      fontSize: 23,
      fontWeight: '900',
      letterSpacing: 0,
    },
    metaLabelAccent: {
      color: p.info,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0,
    },
    positiveText: {
      color: p.success,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundCard: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: shape.controlRadius,
      backgroundColor: p.surface,
      ...surfaceLift,
    },
    roundSelected: {
      backgroundColor: p.accent,
      borderColor: p.accent,
      ...accentLift,
    },
    roundNumber: {
      color: p.info,
      fontSize: 17,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundTextSelected: {
      color: p.onAccent,
    },
    roundTitle: {
      color: p.foreground,
      fontSize: 14,
      fontWeight: '900',
      letterSpacing: 0,
    },
    roundDetail: {
      color: p.muted,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0,
    },
    pointValue: {
      color: p.accent,
      fontSize: 24,
      fontWeight: '900',
      letterSpacing: 0,
    },
    smallButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
    },
    smallButtonText: {
      color: p.foreground,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    timerCard: {
      minHeight: 122,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderWidth: 1,
      borderColor: p.danger,
      borderRadius: shape.cardRadius,
      backgroundColor: p.surfaceAlt,
      ...surfaceLift,
    },
    timerText: {
      color: p.foreground,
      fontSize: 44,
      fontWeight: '900',
      letterSpacing: 0,
    },
    timerSubtext: {
      color: p.subtleText,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0,
    },
    secretCard: {
      minHeight: 174,
      justifyContent: 'space-between',
      gap: 10,
      padding: 16,
      borderRadius: shape.cardRadius,
      backgroundColor: p.accent,
      ...accentLift,
    },
    secretWord: {
      color: p.onAccent,
      fontSize: 30,
      fontWeight: '900',
      letterSpacing: 0,
    },
    forbiddenWord: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: shape.controlRadius,
      backgroundColor: p.overlayStrong,
    },
    forbiddenText: {
      color: p.accent,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 0,
    },
    navWrap: {
      height: 96,
      justifyContent: 'center',
      paddingTop: 10,
      paddingHorizontal: 24,
      paddingBottom: 20,
      backgroundColor: 'transparent',
    },
    navPill: {
      height: 60,
      flexDirection: 'row',
      gap: 4,
      padding: 5,
      borderWidth: 1,
      borderColor: p.line,
      borderRadius: 36,
      backgroundColor: p.overlayStrong,
      ...accentLift,
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      borderRadius: 26,
    },
    navItemActive: {
      backgroundColor: p.navActive,
      ...accentLift,
    },
    navLabel: {
      color: p.muted,
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0,
    },
    navLabelActive: {
      color: p.onAccent,
      fontWeight: '900',
    },
  });
}
